version: "3.8"

services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    command: ["uv", "run", "uvicorn", "src.backend.app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://docker-backend:8000
    command: ["npm", "run", "dev"]

networks:
  app-network:
    driver: bridge
